resolver: lts-10.5
packages:
  - .
local-bin-path: .stack-bin/
extra-deps:
  - hakyll-4.11.0.0
  - pandoc-2.1.1
  - pandoc-citeproc-0.13.0.1
nix:
  packages:
    - zlib.dev
    - zlib.out
  pure: false
ghc-options:
  "ColEx": -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints 
