resolver: lts-13.19
packages:
  - .
local-bin-path: .stack-bin/
extra-deps:
  - hakyll-4.12.5.2
  - lrucache-1.2.0.1
nix:
  packages:
    - zlib.dev
    - zlib.out
  pure: false
  path: ["nixpkgs=https://github.com/NixOS/nixpkgs/archive/e829aeefa35cb1c0b321c08e5b4dd2825911c050.tar.gz"]
ghc-options:
  "ColEx": -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
