// flow-typed signature: aac8da6a56bb1a4fbba471b65974630f
// flow-typed version: <<STUB>>/d3_v3.5.17/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3' {
  declare module.exports: any;
}
